### ISSUE TITLE
PreFlowError running API Connect v5.0.8.0 (apiconnect v2.7.28) Microgateway

### ISSUE THREAD

**Issue by kevinom** [strongloop/microgateway#87]
When running on the Microgateway, calls to API endpoints fail with the message:
{"name":"PreFlowError","message":"unable to process the request"}

Create a new API with any hardcoded target URL in the Invoke properties.
If you run the Test option from the Designer, it gives the error mentioned above.

**Comment by ozairs** [comment]
The preflow error usually occurs before execution of the API assembly. 

Can you run the same request outside of the Test tool within the designer (ie using curl).

Are you sure you have the right clientid, clientsecret, URI (remember that incoming API is combination of base_path + API).

**Comment by sunnygoel8** [comment]
Hi @ozairs , 

I'm getting same issue while running api locally on MicroGateway. Tested via. Soap UI, Postman, curl but same result. Verified Client id, secret, URI etc. and everything looks fine. 

Pushed loopback application & related product on Bluemix. Working fine there because it's running on DataPower gateway..

**Comment by jgeddes2001** [comment]
@kevinom I tried the scenario you describe.. seems to work for me based on current code I get from `npm install -g apiconnect`..
Can you include the swagger you are using?

**Comment by kevinom** [comment]
Hi Jeremy - here is the YAML file - had to ZIP it because it doesn't let me upload .YAML
[savings_1.0.0.zip](https://github.com/strongloop/microgateway/files/1322348/savings_1.0.0.zip)

**Comment by jgeddes2001** [comment]
yeah.. Something is different about our environments.. I can't seem to recreate the problem using your swagger in my env.. 

`https://localhost:4002/savings/Plans/estimate`
returns:
```
{
  "balance": 8933.42
}
```

**Comment by kevinom** [comment]
Are you perhaps running with the IBM SDK for Node.js?
I get the preflow error running apiconnect 2.7.28 on two systems:
One with node v4.6.1 & npm 4.4.4
The other with node v6.11.3 & npm 3.10.10

**Comment by jgeddes2001** [comment]
So, I played around some more and realized I hadn't really updated apiconnect correctly to:
```
$ apic --version
API Connect: v5.0.8.0 (apiconnect: v2.7.28)
```

I was able to recreate the problem `Error: api-loader failed to load any API` .. and workaround the problem by redoing the npm dependencies.. 

Work around:
```
cd /usr/local/lib/node_modules/apiconnect/node_modules/microgateway
rm -rf node_modules
sudo npm i
```

This is some sort of packaging issue.. 

Seems like this is related to https://github.com/strongloop/loopback-datasource-juggler/issues/1467

**Comment by kevinom** [comment]
The workaround worked for me.
Thanks a lot Jeremy.

**Comment by sunnygoel8** [comment]
Thanks @jgeddes2001 .. It's working fine for me as well.

**Comment by jgeddes2001** [comment]
Great!.. I'm still chasing what changes need to be made on the apiconnect shrinkwrap to line up with microgateway's dependencies.. I have a few suspects, but not there yet..

**Comment by kevinom** [comment]
Hi Jeremy,
Don't know whether this is related to the previous issue, but the Explore option is not letting me POST a note in the sample notes application that come with Loopback/API Connect.
When I run Try it with generated data on a POST https://localhost:4002/api/Notes, it returns a 422 error:
{
  "error": {
    "statusCode": 422,
    "name": "ValidationError",
    "message": "The `Note` instance is not valid. Details: `id` can't be set (value: 40.39781222).",
    "details": {
      "context": "Note",
      "codes": {
        "id": [
          "absence"
        ]
      },
      "messages": {
        "id": [
          "can't be set"
        ]
      }
    },
    "stack": "ValidationError: The `Note` instance is not valid. Details: `id` can't be set (value: 40.39781222).\n    at /home/student/samples/notes/node_modules/loopback-datasource-juggler/lib/dao.js:398:12\n    at ModelConstructor.<anonymous> (/home/student/samples/notes/node_modules/loopback-datasource-juggler/lib/validations.js:567:11)\n    at ModelConstructor.next (/home/student/samples/notes/node_modules/loopback-datasource-juggler/lib/hooks.js:93:12)\n    at ModelConstructor.<anonymous> (/home/student/samples/notes/node_modules/loopback-datasource-juggler/lib/validations.js:564:23)\n    at ModelConstructor.trigger (/home/student/samples/notes/node_modules/loopback-datasource-juggler/lib/hooks.js:83:12)\n    at ModelConstructor.Validatable.isValid (/home/student/samples/notes/node_modules/loopback-datasource-juggler/lib/validations.js:530:8)\n    at /home/student/samples/notes/node_modules/loopback-datasource-juggler/lib/dao.js:394:9\n    at doNotify (/home/student/samples/notes/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)\n    at doNotify (/home/student/samples/notes/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)\n    at doNotify (/home/student/samples/notes/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)\n    at doNotify (/home/student/samples/notes/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)\n    at Function.ObserverMixin._notifyBaseObservers (/home/student/samples/notes/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)\n    at Function.ObserverMixin.notifyObserversOf (/home/student/samples/notes/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)\n    at Function.ObserverMixin._notifyBaseObservers (/home/student/samples/notes/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)\n    at Function.ObserverMixin.notifyObserversOf (/home/student/samples/notes/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)\n    at Function.ObserverMixin._notifyBaseObservers (/home/student/samples/notes/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)"
  }
}

**Comment by jgeddes2001** [comment]
@kevinom think that's coming from your actual app.. not related to microgateway.. Sounds like your datatypes aren't lining up..

**Comment by sjc-code** [comment]
Hopefully this is the issue tracking the underlying cause of these symptoms . . .
https://developer.ibm.com/answers/questions/404975/facing-error-with-the-api-designer-tool-kit.html
https://stackoverflow.com/questions/46495030/apiconnect-failing-to-receive-data-from-the-server

**Comment by rickchoi** [comment]
I still experience this issue even in v2.7.30, and the workaround shared by @jgeddes2001 (redoing npm dependencies in microgateway modules) works well. I'm just wondering why this issue's not even resolved in the newly released version and there's no official announcement or notes from product team for the issue..

**Comment by KarimPanni** [comment]
@jgeddes2001 is there a reason the workaround you provided would not work on windows 10?

Work around:

cd /usr/local/lib/node_modules/apiconnect/node_modules/microgateway
rm -rf node_modules
sudo npm i

**Comment by jgeddes2001** [comment]
@KarimPanni I'm guessing if the workaround doesn't work on your windows 10 in your environment is one of three things.. 
1. windows' directory structure puts global npm modules in a different location.. https://stackoverflow.com/questions/33819757/global-npm-install-location-on-windows
2. npm version difference?
3. different problem?

**Comment by smartmouse** [comment]
This issue should be resolved with APIConnect v5.0.8.1 and microagteway 1.6.6.

**Comment by sunnygoel8** [comment]
Hi @jgeddes2001 ,

I'm facing the same issue with API Connect v 5.0.8.3 I tried the workaround you mentioned above in this thread but that didn't work for me. Here's the NPM and Windows version, I'm running on my machine.

Could you please help me fix this issue ? Thanks. 

npm v 5.6.0
Windows 10 Enterprise

**Comment by saywow** [comment]
we have not yet support npm v5.6.x in API Apiconnect  v.5.0.8.3.
We support node 6.x and npm 3.x only

**Comment by sunnygoel8** [comment]
@saywow , Thanks for your response. It means, I'll need to downgrade the Node and npm version on my machine. I'll give it a try and let you know how it goes..

**Comment by smartmouse** [comment]
Tentatively in next up coming release. Which node version are you using? Node 10.x or just node 8.x ?

**Comment by sunnygoel8** [comment]
Hi @smartmouse ,

I was using 8.x , downgraded that to v 6.x and tried installing the APIc toolkit afterwards. But install itself is failing now. So I'm thinking to upgrade node version back to 8.x (which comes by default with npm 5.6) and then will try to install APIc toolkit again..

**Comment by asraro** [comment]
Getting the same error when i run the curl command:

C:\Windows\system32>curl --request POST --url https://localhost:4002/api/Notes --header 'accept: application/json' --header 'content-type: application/json' --header 'x-ibm-client-id: default' --heade
r 'x-ibm-client-secret: SECRET' --data '{"title":"abucanun","content":"deto","id":30.63861523}' -k
{"name":"PreFlowError","message":"unable to process the request"}curl: (6) Could not resolve host: application
curl: (6) Could not resolve host: application
curl: (6) Could not resolve host: default'
curl: (6) Could not resolve host: SECRET'

Here's my version:
--------------------
C:\Windows\system32>apic -v
API Connect: v5.0.8.4-iFix (apiconnect: v2.8.29)

C:\Windows\system32>npm -v
6.4.0

C:\Windows\system32>node -v
v8.11.3

**Comment by jeanabraham** [comment]
Folks, 

I getting the same error:
```
// https://127.0.0.1:4002/
{
  "name": "PreFlowError",
  "message": "unable to process the request"
}

```
I already tried without success:
```
cd /usr/local/lib/node_modules/apiconnect/node_modules/microgateway
rm -rf node_modules
sudo npm i

```

Here are the versions that I'm using:
```
jean:apic$node -v
v8.15.0
jean:apic$npm -v
6.4.1
jean:apic$apic -v
API Connect: v5.0.8.5 (apiconnect: v3.0.17)
jean:apic$
```

Any help would be appreciated? Thanks!
